CREATE DATABASE crud_db DEFAULT CHARACTER SET utf8mb4;

USE crud_db;

CREATE TABLE usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL DEFAULT '',
    telefone VARCHAR(20)
);